### ISSUE TITLE
2.0: MSI Installer should update Branta if version already exists

### ISSUE THREAD

**Issue by kylemccullen** [BrantaOps/branta-windows#102]
When a user downloads and runs a msi when they have an older version of Branta installed they see this

![image](https://github.com/BrantaOps/branta-windows/assets/110685100/e5317376-775a-40d8-8ef4-1ad1b9c16d7a)

Setup the installer so that it installs over the old version

**Comment by keith-gardner** [comment]
💯

**Comment by kylemccullen** [comment]
According to this answer

https://stackoverflow.com/questions/7330867/visual-studio-how-to-automatically-uninstall-previous-installed-version

Installing a different binary with the same ProductVersion and ProductCode will result in an error during install.

Each release going forward will have a different ProductVersion and ProductCode.
