### ISSUE TITLE
Any program with "Branta" in the name causes Branta to not run

### ISSUE THREAD

**Issue by kylemccullen** [BrantaOps/branta-windows#153]
Branta checks to see if any process contains the name Branta, and if one is found open that window instead of starting a new instance.  Other windows may contain the name "Branta" (for example having File Explorer open with a folder named Branta)

**Comment by keith-gardner** [comment]
What is the Windows community standard for solving this?

**Comment by kylemccullen** [comment]
> What is the Windows community standard for solving this?

I ended up checking the Process info to confirm the process is the Branta executable running to solve this. Im not sure what the standard way of handling this is. More research would be required.
