### ISSUE TITLE
Version Text

### ISSUE THREAD

**Issue by keith-gardner** [BrantaOps/branta-windows#40]
Dynamically update UI based on variable or other mechanism

<img width="693" alt="Screen Shot 2024-01-27 at 4 01 33 PM" src="https://github.com/BrantaOps/branta-windows/assets/74844722/b32c6bba-fd9c-4369-8d4a-523149b0ebbe">

**Comment by kylemccullen** [comment]
Version text is dynamically updated
```cs
var version = Assembly.GetEntryAssembly()!.GetCustomAttribute<AssemblyInformationalVersionAttribute>()!.InformationalVersion
```

The exe was built prior to version bump. New exe with proper release version has be uploaded to release v1.0.0
